trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dmaven.test.failure.ignore=true'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'reports/Extentreport.html'
    testRunTitle: 'Selenium Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'reports'
    artifactName: 'selenium-reports'
